#!/bin/bash

CARD_NUMBER=0
BRAVENESS=20
CARDPATH="/sys/class/drm/card$CARD_NUMBER/device/"

ACTION=$1
THING=$2
PARAMETER=$3  #and onward, should implement proper arg getting

function main {

	cd $CARDPATH

	case $ACTION in

		get )
		parse_get ;;

		set )
		parse_set ;;
		
		reset )
		reset ;;

		help )
		print_help ;;

		*)
		print_help ;;

	esac
}

###############################################################################
## GET COMMANDS

function parse_get {
	case $THING in
		core )
		get_core_clock ;;

		core-oc )
		get_core_oc ;;

		mem|memory )
		get_memory_clock ;;

		mem-oc|memory-oc )
		get_memory_oc ;;

		pcie )
		get_pcie_speed ;;

		*)
		print_get_help;;
	esac
}

function get_core_clock {
	if [ "$PARAMETER" = "table" ]
	then
		cat pp_dpm_sclk
	else
		cat pp_dpm_sclk | grep -F '*'
	fi
}

function get_core_oc {
	cat pp_sclk_od
}

function get_memory_oc {
	cat pp_mclk_od
}

function get_memory_clock {
	if [ "$PARAMETER" = "table" ]
	then
		cat pp_dpm_mclk
	else
		cat pp_dpm_mclk | grep -F '*'
	fi
}

function get_pcie_speed {
	if [ "$PARAMETER" = "table" ]
	then
		cat pp_dpm_pcie
	else
		cat pp_dpm_pcie | grep -F '*'
	fi
}

###############################################################################
## SET COMMANDS

function parse_set {

	case $THING in
		core-oc )
		sanitize_oc
		set_core_oc $PARAMETER ;;

		mem-oc|memory-oc )
		sanitize_oc
		set_memory_oc $PARAMETER ;;

		*)
		print_set_help;;
	esac
}

function set_core_oc {
	sudo bash -c "echo $1 > pp_sclk_od"
}

function set_memory_oc {
	sudo bash -c "echo $1 > pp_mclk_od"
}


###############################################################################
## UTIL COMMANDS

function sanitize_oc {

	case $PARAMETER in
	''|*[!0-9]*)
	echo "Not an overclock percentage value"
	exit 1 ;;

	*)
	if [ $PARAMETER -gt $BRAVENESS ]
	then
		echo "Unsafe overclock percentage value"
		exit 1
	fi ;;

	esac
}

function reset {
	set_core_oc 0
	set_memory_oc 0
}

###############################################################################
## HELP COMMANDS

function print_help {
	echo $"Usage: $0 {get|set|reset|help}"
	exit 1
}

function print_get_help {
	echo $"Usage: $0 get {core|mem|core-oc|mem-oc|pcie} [table]"
	exit 1
}

function print_set_help {
	echo $"Usage: $0 set {core|mem} {0-$BRAVENESS}"
	exit 1
}

## Runs the main function
main


